server:
  port: 8087

spring:
  application:
    name: payments-service

  config:
    import: optional:configserver:http://localhost:8888

  # ======================
  # Kafka
  # ======================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

  # ======================
  # (OPTIONNEL) DB
  # uniquement si tu veux persister les notifications
  # ======================
  datasource:
    url: jdbc:postgresql://localhost:5432/smartiadev_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# ======================
# Eureka
# ======================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: HzuHlbBi+nyXGNVWXYo9I7ojNnxfE8FVnmt1jV0nMeU=
  expiration: 86400000

# ======================
# Logging (utile au d√©but)
# ======================
logging:
  level:
    org.springframework.kafka: INFO
    com.smartiadev.notif_service: DEBUG
